"""Type stubs for etherscan module - enables IDE autocomplete for dynamically bound methods."""

from typing import List, Dict, Any
from etherscan.enums.chainids_enum import ChainidsEnum

class Etherscan:
    """
    A minimal, yet complete, Python API for Etherscan.io.

    All methods are dynamically bound at instantiation.
    Chain selection is done per method call via the chain_id parameter.
    This stub file provides type hints for IDE support.
    """

    # Class attribute for chain IDs
    Chain: ChainidsEnum

    def __new__(cls, api_key: str) -> 'Etherscan': ...

    @classmethod
    def from_config(cls, api_key: str, config_path: str) -> 'Etherscan': ...
    
    # Accounts module methods
    def get_erc20_token_transfer_events_by_address(self, address: str, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    def get_erc20_token_transfer_events_by_address_and_contract_paginated(self, contract_address: str, address: str, page: int, offset: int, sort: str, chain_id: int = ...) -> str: ...
    def get_erc20_token_transfer_events_by_contract_address_paginated(self, contract_address: str, page: int, offset: int, sort: str, chain_id: int = ...) -> str: ...
    def get_erc721_token_transfer_events_by_address(self, address: str, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    def get_erc721_token_transfer_events_by_address_and_contract_paginated(self, contract_address: str, address: str, page: int, offset: int, sort: str, chain_id: int = ...) -> str: ...
    def get_erc721_token_transfer_events_by_contract_address_paginated(self, contract_address: str, page: int, offset: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_balance(self, address: str, chain_id: int = ...) -> str: ...
    def get_eth_balance_multiple(self, addresses: List, chain_id: int = ...) -> str: ...
    def get_internal_txs_by_address(self, address: str, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    def get_internal_txs_by_address_paginated(self, address: str, page: int, offset: int, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    def get_internal_txs_by_block_range_paginated(self, startblock: int, endblock: int, page: int, offset: int, sort: str, chain_id: int = ...) -> str: ...
    def get_internal_txs_by_txhash(self, txhash: str, chain_id: int = ...) -> str: ...
    def get_mined_blocks_by_address(self, address: str, chain_id: int = ...) -> str: ...
    def get_mined_blocks_by_address_paginated(self, address: str, page: int, offset: int, chain_id: int = ...) -> str: ...
    def get_normal_txs_by_address(self, address: str, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    def get_normal_txs_by_address_paginated(self, address: str, page: int, offset: int, startblock: int, endblock: int, sort: str, chain_id: int = ...) -> str: ...
    
    # Blocks module methods
    def get_block_number_by_timestamp(self, timestamp: int, closest: str, chain_id: int = ...) -> str: ...
    def get_block_reward_by_block_number(self, block_no: str, chain_id: int = ...) -> str: ...
    def get_est_block_countdown_time_by_block_number(self, block_no: str, chain_id: int = ...) -> str: ...
    
    # Contracts module methods
    def get_contract_abi(self, address: str, chain_id: int = ...) -> str: ...
    def get_contract_source_code(self, address: str, chain_id: int = ...) -> str: ...
    
    # Gastracker module methods
    def get_est_confirmation_time(self, gas_price: int, chain_id: int = ...) -> str: ...
    def get_gas_oracle(self, chain_id: int = ...) -> str: ...
    
    # Pro module methods
    def get_daily_average_block_size(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_average_block_time(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_average_gas_limit(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_average_network_difficulty(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_average_network_hash_rate(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_block_count_and_rewards(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_block_rewards(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_network_utilization(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_new_address_count(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_tx_count(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_daily_uncle_block_count_and_rewards(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_daily_average_gas_price(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_daily_network_tx_fee(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_daily_total_gas_used(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_hist_daily_market_cap(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_eth_hist_price(self, start_date: int, end_date: int, sort: str, chain_id: int = ...) -> str: ...
    def get_hist_erc20_token_account_balance_for_token_contract_address_by_block_no(self, contract_address: str, address: str, block_no: int, chain_id: int = ...) -> str: ...
    def get_hist_erc20_token_total_supply_by_contract_address_and_block_no(self, contract_address: str, block_no: int, chain_id: int = ...) -> str: ...
    def get_hist_eth_balance_for_address_by_block_no(self, address: str, block_no: int, chain_id: int = ...) -> str: ...
    def get_token_info_by_contract_address(self, contract_address: str, chain_id: int = ...) -> str: ...
    
    # Proxy module methods
    def get_proxy_block_by_number(self, tag: str, chain_id: int = ...) -> str: ...
    def get_proxy_block_number(self, chain_id: int = ...) -> str: ...
    def get_proxy_block_transaction_count_by_number(self, tag: str, chain_id: int = ...) -> str: ...
    def get_proxy_call(self, to: str, data: str, chain_id: int = ...) -> str: ...
    def get_proxy_code_at(self, address: str, chain_id: int = ...) -> str: ...
    def get_proxy_est_gas(self, to: str, data: str, value: str, gas_price: str, gas: str, chain_id: int = ...) -> str: ...
    def get_proxy_gas_price(self, chain_id: int = ...) -> str: ...
    def get_proxy_storage_position_at(self, position: str, address: str, chain_id: int = ...) -> str: ...
    def get_proxy_transaction_by_block_number_and_index(self, tag: str, index: str, chain_id: int = ...) -> str: ...
    def get_proxy_transaction_by_hash(self, txhash: str, chain_id: int = ...) -> str: ...
    def get_proxy_transaction_count(self, address: str, chain_id: int = ...) -> str: ...
    def get_proxy_transaction_receipt(self, txhash: str, chain_id: int = ...) -> str: ...
    def get_proxy_uncle_by_block_number_and_index(self, tag: str, index: str, chain_id: int = ...) -> str: ...
    
    # Stats module methods
    def get_eth_last_price(self, chain_id: int = ...) -> str: ...
    def get_eth_nodes_size(self, start_date: str, end_date: str, client_type: str, sync_mode: str, sort: str, chain_id: int = ...) -> str: ...
    def get_total_eth_supply(self, chain_id: int = ...) -> str: ...
    
    # Tokens module methods
    def get_acc_balance_by_token_and_contract_address(self, contract_address: str, address: str, chain_id: int = ...) -> str: ...
    def get_total_supply_by_contract_address(self, contract_address: str, chain_id: int = ...) -> str: ...
    
    # Transactions module methods
    def get_contract_execution_status(self, txhash: str, chain_id: int = ...) -> str: ...
    def get_tx_receipt_status(self, txhash: str, chain_id: int = ...) -> str: ...
    
